### ISSUE TITLE
gunicorn preload option

### ISSUE THREAD

**Issue by jpcope** [rewardStyle/generator-plait#4]
@adambullmer Please consider adding the preload option to the base gunicorn config file https://github.com/rewardStyle/generator-plait/blob/master/app/templates/_gunicorn.conf

@misakwa @prestontimmons @CodyMorris and @dharris001 can be more descriptive as to why we wish to use this option moving forward.

References to previous lessons learned:
https://my.rewardstyle.com/wiki/display/DEVO/11.19.15+-+Census+deployment+cancellation

**Comment by jpcope** [comment]
https://gunicorn-docs.readthedocs.org/en/develop/configure.html#preload-app

**Comment by jpcope** [comment]
Also adding @fjordan since this is an overall software architectural decision we may wish to use everywhere in our python stack where gunicorn is used. It makes our deployments overall way more stable and less likely to suffer from any backlogged requests in the case of hotfixes or rollbacks.

**Comment by adambullmer** [comment]
I do have this option currently listed in the README for [Running the Service](https://github.com/rewardStyle/generator-plait/blob/master/app/templates/_README.md#running-the-service). Maybe a config option would be better through...

**Comment by misakwa** [comment]
From my experience with census I realized that the forking process misses some of the imports (specifically the `rsthrift` imports) after `execve` which caused those processes to fail. I suggested adding the preload option because it only loads the imports once in the main process before forking which will guarantee that there are no discrepancies in the forked processes. In our case I think the race is in creating the imports which creates the rsthrift module objects at runtime.
I saw similar reports docker/docker-registry#483 and docker/docker-registry#655
